#!groovy

// Generated by IBM TransformationAdvisor
// Wed Jan 23 09:17:26 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'bookmydoc'
    mvnCommands = '--version'
    test='false'
}